#inherit_from: .rubocop_todo.yml
require: rubocop-rspec
AllCops:
  Include:
    - '**/Gemfile'
    - Rakefile
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - bin/webpack
    - db/**
    - config/**
    - app/assets/javascript
    - app/javascript
Metrics/MethodLength:   
  Max: 20

Documentation:  
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
